name: joplin-stack

# Based on https://github.com/laurent22/joplin/blob/dev/docker-compose.server.yml

services:

  joplin-postgres:
    image: postgres:16
    container_name: joplin-postgres
    hostname: joplin-postgres
    volumes:
      - ../data/postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file: joplin-server-env
    environment:
      - POSTGRES_USER=joplin
      - POSTGRES_DB=joplindb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  joplin-server:
    # https://hub.docker.com/r/joplin/server/tags
    image: joplin/server:3.5.2
    container_name: joplin-server
    hostname: joplin-server
    volumes:
      - ../data/joplin/joplin-storage:/joplin-storage
    # Uncomment if using the optional joplin-cron export system
    #  - ../data/export:/export
    ports:
      - 22300:22300
    restart: unless-stopped
    depends_on:
      - joplin-postgres
    env_file: joplin-server-env
    environment:
      - APP_PORT=22300
      - DB_CLIENT=pg
      - POSTGRES_HOST=joplin-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=joplin
      - POSTGRES_DATABASE=joplindb
      - STORAGE_DRIVER=Type=Filesystem; Path=/joplin-storage
      # Uncomment if starting the server results in `Cannot retrieve the network time from pool.ntp.org` error due to poor upstream container design
      # - NTP_SERVER=time.nist.gov:123
    # The container contains no healthcheck by default, but this works well enough
    healthcheck:
      test:
        - "CMD-SHELL"
        - |
          node -e "
          const { APP_PORT: port = 22300, APP_BASE_URL: url } = process.env;
          const { host, origin } = new URL(url);
          require('http').get({ host: 'localhost', port: port, path: '/api/ping', headers: { host, origin } }, r => process.exitCode = r.statusCode === 200 ? 0 : 1).on('error', () => process.exitCode = 1)
          "
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Optional webapp
  # Uncomment this service to build and deploy the webapp on port 22380
#  joplin-webapp:
#    container_name: joplin-webapp
#    hostname: joplin-webapp
#    build:
#      context: .
#      dockerfile: joplin-webapp-Dockerfile
#    ports:
#      - 22380:80
#    restart: unless-stopped

  # Optional exports
  # Uncomment and configure this service to perform regular exports at a user-level
  # Make sure to uncomment the /export path in joplin-server as well
  # By default, set to run at 11:50PM Eastern Time and retain 30 days of history
  # You must check README.md before enabling this or it won't work!
#  joplin-cron:
#    # https://hub.docker.com/r/whefter/cron/tags
#    image: whefter/cron:v1.0.8
#    container_name: joplin-cron
#    hostname: joplin-cron
#    network_mode: none
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    restart: unless-stopped
#    depends_on:
#      - joplin-server
#    environment:
#      TZ: America/Toronto
#      CRON_JOPLIN_EXPORT: |
#        50 23 * * * date && docker exec joplin-server bash -c 'BACKUP_RETENTION_DAYS=30; for PROFILE_PATH in /export/profiles/*/; do USER_NAME=$(basename "$$PROFILE_PATH"); npx --silent --yes joplin@3.5.1 --profile "$$PROFILE_PATH" sync && npx --silent --yes joplin@3.5.1 --profile "$$PROFILE_PATH" export --format jex "/export/backups/$${USER_NAME}_$(date -u +%Y%m%d_%H%M%SZ).jex"; done; find /export/backups/ -name "*.jex" -type f -mtime +$$BACKUP_RETENTION_DAYS -delete'
