# Joplin Server IP or hostname
upstream joplin_server {
    server internal-joplin-host:22300;
    keepalive 16;
}

# Joplin Webapp IP or hostname
upstream joplin_webapp {
    server internal-joplin-host:22380;
    keepalive 16;
}


# Redirect HTTP to HTTPS
server {
    server_name subdomain.domain.tld;
    listen 80;
    listen [::]:80;
    return 301 https://$http_host$request_uri;
}

# HTTPS host
server {
    server_name subdomain.domain.tld;
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    client_max_body_size 2048M;

    proxy_pass_header Content-Type;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;

    # Joplin Server hosted on `/joplin` path
    location /joplin/ {
        proxy_pass http://joplin_server/;

        ########
        # Block external access from public IP space
        # Comment or remove the following lines ONLY once the service has been configured if you want to allow access from non-private IPs
        # Do not ever expose publicly before setting up
        allow 10.0.0.0/8;
        allow 172.16.0.0/12;
        allow 192.168.0.0/16;
        deny all;
        ########
    }

    # Joplin Webapp server on base root `/` path
    location / {
        proxy_pass http://joplin_webapp/;

        ########
        # Block external access from public IP space
        # Comment or remove the following lines if you want to allow access from non-private IPs
        allow 10.0.0.0/8;
        allow 172.16.0.0/12;
        allow 192.168.0.0/16;
        deny all;
        ########
    }


    ssl_certificate /etc/letsencrypt/live/subdomain.domain.tld/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/subdomain.domain.tld/privkey.pem; # managed by Certbot
}
